<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30348" started-at="2021-09-28T10:19:53 IST" finished-at="2021-09-28T10:20:23 IST">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="30348" started-at="2021-09-28T10:19:53 IST" finished-at="2021-09-28T10:20:23 IST">
      <class name="com.Banking.testCases.LoginDDT">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.Banking.testCases.LoginDDT@6b9651f3]" name="initialize" is-config="true" duration-ms="1502" started-at="2021-09-28T10:19:55 IST" finished-at="2021-09-28T10:19:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.Banking.testCases.LoginDDT@6b9651f3]" name="LoginDDT" duration-ms="6652" started-at="2021-09-28T10:20:04 IST" data-provider="LoginData" finished-at="2021-09-28T10:20:10 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr354555]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jEpAsyz]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method status="FAIL" signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.Banking.testCases.LoginDDT@6b9651f3]" name="LoginDDT" duration-ms="2841" started-at="2021-09-28T10:20:10 IST" data-provider="LoginData" finished-at="2021-09-28T10:20:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mytest]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.Banking.testCases.LoginDDT.LoginDDT(LoginDDT.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method status="PASS" signature="LoginDDT(java.lang.String,java.lang.String)[pri:0, instance:com.Banking.testCases.LoginDDT@6b9651f3]" name="LoginDDT" duration-ms="3783" started-at="2021-09-28T10:20:13 IST" data-provider="LoginData" finished-at="2021-09-28T10:20:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr354555]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jEpAsyz]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.Banking.testCases.LoginDDT@6b9651f3]" name="teardown" is-config="true" duration-ms="128" started-at="2021-09-28T10:20:23 IST" finished-at="2021-09-28T10:20:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.Banking.testCases.LoginDDT -->
      <class name="com.Banking.testCases.LoginTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.Banking.testCases.LoginTest@3e57cd70]" name="initialize" is-config="true" duration-ms="1614" started-at="2021-09-28T10:19:57 IST" finished-at="2021-09-28T10:19:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.Banking.testCases.LoginTest@3e57cd70]" name="loginTest" duration-ms="4342" started-at="2021-09-28T10:19:58 IST" finished-at="2021-09-28T10:20:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.Banking.testCases.LoginTest@3e57cd70]" name="teardown" is-config="true" duration-ms="148" started-at="2021-09-28T10:20:23 IST" finished-at="2021-09-28T10:20:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.Banking.testCases.LoginTest -->
      <class name="com.Banking.testCases.HomePageTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.Banking.testCases.HomePageTest@38bc8ab5]" name="initialize" is-config="true" duration-ms="2540" started-at="2021-09-28T10:19:53 IST" finished-at="2021-09-28T10:19:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="addNewCustomer()[pri:0, instance:com.Banking.testCases.HomePageTest@38bc8ab5]" name="addNewCustomer" duration-ms="5541" started-at="2021-09-28T10:20:17 IST" finished-at="2021-09-28T10:20:23 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.Banking.testCases.HomePageTest.addNewCustomer(HomePageTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.Banking.testCases.HomePageTest@38bc8ab5]" name="teardown" is-config="true" duration-ms="88" started-at="2021-09-28T10:20:23 IST" finished-at="2021-09-28T10:20:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.Banking.testCases.HomePageTest -->
    </test> <!-- Login Test -->
  </suite> <!-- Suite -->
</testng-results>
